# Settings for math eval


ground_truth: MATH_benchmarks/benchmark_prealgebra_1-1.json
number_of_runs: 1
log_folder: logs
log_file: null
task_filter: null

tools: math_tools
model: "gpt-3.5-turbo-0125"
#model: "gpt-4-turbo-2024-04-09"
embedding_model: "text-embedding-3-large"

tulip_top_k: 5
search_similarity_threshold: null

agents:
    BaseAgent: True
    NaiveToolAgent: False
    CotToolAgent: True
    MinimalTulipAgent: False
    NaiveTulipAgent: False
    CotTulipAgent: True
    InformedCotTulipAgent: False
    PrimedCotTulipAgent: False
    OneShotCotTulipAgent: False
    AutoTulipAgent: False

colors:
    BaseAgent: "#a6a6a6"
    NaiveToolAgent: "#8cb3d9"
    CotToolAgent: "#6699ff"
    MinimalTulipAgent: "#9999ff"
    NaiveTulipAgent: "#9966ff"
    CotTulipAgent: "#9933ff"
    InformedCotTulipAgent: "#9900ff"
    PrimedCotTulipAgent: "#cc66ff"
    OneShotCotTulipAgent: "#cc33ff"
    AutoTulipAgent: "#660066"