# Settings for math eval


ground_truth: MATH_benchmarks/benchmark_prealgebra_1-5.json
log_folder: logs
log_file: null
task_filter: null

tools: math_tools
model: "gpt-3.5-turbo-0125"

agents:
    BaseAgent: True
    NaiveToolAgent: True
    CotToolAgent: True
    MinimalTulipAgent: True
    NaiveTulipAgent: True
    CotTulipAgent: True
    AutoTulipAgent: False

colors:
    BaseAgent: "#a6a6a6"
    NaiveToolAgent: "#8cb3d9"
    CotToolAgent: "#6699ff"
    MinimalTulipAgent: "#9999ff"
    NaiveTulipAgent: "#9966ff"
    CotTulipAgent: "#9933ff"
    AutoTulipAgent: "#9900ff"
