# Ablation settings for math eval

ground_truth: math_tasks.json
tools: math_tools
log_folder: logs
log_file: null

agents:
    BaseAgent: True
    NaiveToolAgent: True
    CotToolAgent: True
    MinimalTulipAgent: True
    NaiveTulipAgent: True
    CotTulipAgent: True
    AutoTulipAgent: False

colors:
    BaseAgent: "#a6a6a6"
    NaiveToolAgent: "#8cb3d9"
    CotToolAgent: "#6699ff"
    MinimalTulipAgent: "#9999ff"
    NaiveTulipAgent: "#9966ff"
    CotTulipAgent: "#9933ff"
    AutoTulipAgent: "#9900ff"
