# Ablation settings for math eval

ground_truth: math_tasks.json

agents:
    BaseAgent: True
    NaiveToolAgent: True
    CotToolAgent: True
    MinimalTulipAgent: True
    NaiveTulipAgent: True
    CotTulipAgent: True
    AutoTulipAgent: False
