# Settings for math eval

ground_truth: math_tasks.json
number_of_runs: 1
log_folder: logs
log_file: null
task_filter: null

tools: math_tools
model: "gpt-3.5-turbo-0125"

agents:
    BaseAgent: False
    NaiveToolAgent: False
    CotToolAgent: True
    MinimalTulipAgent: False
    NaiveTulipAgent: False
    CotTulipAgent: True
    PrunedCotTulipAgent: True
    AutoTulipAgent: False

colors:
    BaseAgent: "#a6a6a6"
    NaiveToolAgent: "#8cb3d9"
    CotToolAgent: "#6699ff"
    MinimalTulipAgent: "#9999ff"
    NaiveTulipAgent: "#9966ff"
    CotTulipAgent: "#9933ff"
    PrunedCotTulipAgent: "#9900ff"
    AutoTulipAgent: "#9900cc"
