# Settings for math eval

ground_truth: math_tasks.json
number_of_runs: 3
log_folder: logs
log_file: null
task_filter: null

tools: math_tools
model: "gpt-3.5-turbo-0125"
embedding_model: "text-embedding-ada-002"

tulip_top_k: 5
search_similarity_threshold: null

agents:
    BaseAgent: True
    NaiveToolAgent: True
    CotToolAgent: True
    MinimalTulipAgent: True
    NaiveTulipAgent: True
    CotTulipAgent: True
    InformedCotTulipAgent: True
    PrunedCotTulipAgent: True
    OneShotCotTulipAgent: True
    AutoTulipAgent: False

colors:
    BaseAgent: "#a6a6a6"
    NaiveToolAgent: "#8cb3d9"
    CotToolAgent: "#6699ff"
    MinimalTulipAgent: "#9999ff"
    NaiveTulipAgent: "#9966ff"
    CotTulipAgent: "#9933ff"
    InformedCotTulipAgent: "#9900ff"
    PrunedCotTulipAgent: "#cc66ff"
    OneShotCotTulipAgent: "#cc33ff"
    AutoTulipAgent: "#660066"
